// generated by blockdb@0.4.0 — do not edit
import { createClient, type Collection, type ClientOptions, type GenericClient } from "blockdb";
import { schema, type Schema, type Records } from "./schema.js";

export interface Db {
  "default-cards-20260721211623": Collection<Schema["default-cards-20260721211623"], Records["default-cards-20260721211623"]>;
}

const DEFAULT_BASE_PATH = "/blockdb";
// This build pre-compressed the manifest. Everything else the manifest points at carries its
// encoding in its own path, but the manifest is fetched before any of that can be read — so it is
// stamped here, by the same build that wrote the file.
const MANIFEST_COMPRESSION = "gzip" as const;

export function connect(opts?: Partial<ClientOptions>): Db {
  const generic: GenericClient<Schema, Records> = createClient<Schema, Records>(schema, {
    basePath: DEFAULT_BASE_PATH,
    manifestCompression: MANIFEST_COMPRESSION,
    ...opts,
  });
  return generic as unknown as Db;
}
