// generated by blockdb@0.3.1 — do not edit
export type DefaultCards20260721211623Colors = "B" | "G" | "R" | "U" | "W";
export type DefaultCards20260721211623ColorIdentity = "B" | "G" | "R" | "U" | "W";
export type DefaultCards20260721211623Games = "arena" | "mtgo" | "paper";

export interface DefaultCards20260721211623 {
  object: string;
  id: string;
  oracle_id?: string;
  multiverse_ids?: unknown;
  mtgo_id?: number;
  arena_id?: number;
  tcgplayer_id?: number;
  cardmarket_id?: number;
  name: string;
  lang: string;
  released_at: string;
  uri: string;
  scryfall_uri: string;
  layout: string;
  highres_image: boolean;
  image_status: string;
  image_updated_at: string;
  image_uris?: unknown;
  mana_cost?: string;
  cmc?: number;
  type_line?: string;
  oracle_text?: string;
  colors?: string[];
  color_identity: string[];
  keywords: string[];
  produced_mana?: unknown;
  all_parts?: unknown;
  legalities?: unknown;
  games: string[];
  reserved: boolean;
  game_changer: boolean;
  foil: boolean;
  nonfoil: boolean;
  finishes?: unknown;
  oversized: boolean;
  promo: boolean;
  reprint: boolean;
  variation: boolean;
  set_id: string;
  set: string;
  set_name: string;
  set_type: string;
  set_uri: string;
  set_search_uri: string;
  scryfall_set_uri: string;
  rulings_uri: string;
  prints_search_uri: string;
  collector_number: string;
  digital: boolean;
  rarity: string;
  card_back_id?: string;
  artist: string;
  artist_ids?: unknown;
  illustration_id?: string;
  border_color: string;
  frame: string;
  full_art: boolean;
  textless: boolean;
  booster: boolean;
  story_spotlight: boolean;
  prices?: unknown;
  related_uris?: unknown;
  purchase_uris?: unknown;
  mtgo_foil_id?: number;
  power?: string;
  toughness?: string;
  flavor_text?: string;
  edhrec_rank?: number;
  penny_rank?: number;
  promo_types?: unknown;
  security_stamp?: string;
  card_faces?: unknown;
  preview?: unknown;
  watermark?: string;
  frame_effects?: unknown;
  loyalty?: string;
  printed_name?: string;
  resource_id?: string;
  tcgplayer_etched_id?: number;
  flavor_name?: string;
  attraction_lights?: unknown;
  color_indicator?: unknown;
  printed_text?: string;
  printed_type_line?: string;
  power_num?: number;
  toughness_num?: number;
  loyalty_num?: number;
  name_fold?: string;
  type_line_fold?: string;
  oracle_text_fold?: string;
  artist_fold?: string;
  flavor_text_fold?: string;
  set_name_fold?: string;
}

export interface Records {
  "default-cards-20260721211623": DefaultCards20260721211623;
}

export const schema = {
  "default-cards-20260721211623": {
    pk: "id",
    fields: {
      object: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"], pruning: [] },
      id: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"], pruning: ["equals", "in", "startsWith"], pk: true },
      oracle_id: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not", "isAbsent", "exists"], pruning: [], absent: true },
      mtgo_id: { kind: "number", operators: ["equals", "in", "gt", "gte", "lt", "lte", "not", "isAbsent", "exists"], pruning: [], absent: true },
      arena_id: { kind: "number", operators: ["equals", "in", "gt", "gte", "lt", "lte", "not", "isAbsent", "exists"], pruning: [], absent: true },
      tcgplayer_id: { kind: "number", operators: ["equals", "in", "gt", "gte", "lt", "lte", "not", "isAbsent", "exists"], pruning: [], absent: true },
      cardmarket_id: { kind: "number", operators: ["equals", "in", "gt", "gte", "lt", "lte", "not", "isAbsent", "exists"], pruning: [], absent: true },
      name: { kind: "string", operators: ["equals", "in", "gt", "gte", "lt", "lte", "startsWith", "endsWith", "contains", "not"], pruning: ["equals", "in", "gt", "gte", "lt", "lte", "startsWith"] },
      lang: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"], pruning: ["equals", "in", "startsWith"] },
      released_at: { kind: "date", operators: ["equals", "in", "gt", "gte", "lt", "lte", "not"], pruning: ["equals", "in", "gt", "gte", "lt", "lte"] },
      uri: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"], pruning: [] },
      scryfall_uri: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"], pruning: [] },
      layout: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"], pruning: [] },
      highres_image: { kind: "boolean", operators: ["equals", "not"], pruning: ["equals"] },
      image_status: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"], pruning: [] },
      image_updated_at: { kind: "date", operators: ["equals", "in", "gt", "gte", "lt", "lte", "not"], pruning: [] },
      image_uris: { kind: "json", operators: ["isAbsent", "exists"], pruning: [], absent: true },
      mana_cost: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not", "isAbsent", "exists"], pruning: ["equals", "in", "startsWith"], absent: true },
      cmc: { kind: "number", operators: ["equals", "in", "gt", "gte", "lt", "lte", "not", "isAbsent", "exists"], pruning: ["equals", "in", "gt", "gte", "lt", "lte"], absent: true },
      type_line: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not", "isAbsent", "exists"], pruning: [], absent: true },
      oracle_text: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not", "isAbsent", "exists"], pruning: [], absent: true },
      colors: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"], pruning: ["equals", "in", "startsWith"], multi: true, absent: true, values: ["B", "G", "R", "U", "W"] },
      color_identity: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"], pruning: ["equals", "in", "startsWith"], multi: true, values: ["B", "G", "R", "U", "W"] },
      keywords: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"], pruning: ["equals", "in", "startsWith"], multi: true },
      produced_mana: { kind: "json", operators: ["isAbsent", "exists"], pruning: [], absent: true },
      all_parts: { kind: "json", operators: ["isAbsent", "exists"], pruning: [], absent: true },
      games: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"], pruning: ["equals", "in", "startsWith"], multi: true, values: ["arena", "mtgo", "paper"] },
      reserved: { kind: "boolean", operators: ["equals", "not"], pruning: ["equals"] },
      game_changer: { kind: "boolean", operators: ["equals", "not"], pruning: ["equals"] },
      foil: { kind: "boolean", operators: ["equals", "not"], pruning: ["equals"] },
      nonfoil: { kind: "boolean", operators: ["equals", "not"], pruning: ["equals"] },
      oversized: { kind: "boolean", operators: ["equals", "not"], pruning: ["equals"] },
      promo: { kind: "boolean", operators: ["equals", "not"], pruning: ["equals"] },
      reprint: { kind: "boolean", operators: ["equals", "not"], pruning: ["equals"] },
      variation: { kind: "boolean", operators: ["equals", "not"], pruning: ["equals"] },
      set_id: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"], pruning: [] },
      set: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"], pruning: ["equals", "in", "startsWith"] },
      set_name: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"], pruning: [] },
      set_type: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"], pruning: [] },
      set_uri: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"], pruning: [] },
      set_search_uri: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"], pruning: [] },
      scryfall_set_uri: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"], pruning: [] },
      rulings_uri: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"], pruning: [] },
      prints_search_uri: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"], pruning: [] },
      collector_number: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"], pruning: [] },
      digital: { kind: "boolean", operators: ["equals", "not"], pruning: ["equals"] },
      rarity: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"], pruning: ["equals", "in", "startsWith"] },
      card_back_id: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not", "isAbsent", "exists"], pruning: [], absent: true },
      artist: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"], pruning: [] },
      artist_ids: { kind: "json", operators: ["isAbsent", "exists"], pruning: [], absent: true },
      illustration_id: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not", "isAbsent", "exists"], pruning: [], absent: true },
      border_color: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"], pruning: [] },
      frame: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"], pruning: [] },
      full_art: { kind: "boolean", operators: ["equals", "not"], pruning: ["equals"] },
      textless: { kind: "boolean", operators: ["equals", "not"], pruning: ["equals"] },
      booster: { kind: "boolean", operators: ["equals", "not"], pruning: ["equals"] },
      story_spotlight: { kind: "boolean", operators: ["equals", "not"], pruning: ["equals"] },
      purchase_uris: { kind: "json", operators: ["isAbsent", "exists"], pruning: [], absent: true },
      mtgo_foil_id: { kind: "number", operators: ["equals", "in", "gt", "gte", "lt", "lte", "not", "isAbsent", "exists"], pruning: [], absent: true },
      power: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not", "isAbsent", "exists"], pruning: ["equals", "in", "startsWith"], absent: true },
      toughness: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not", "isAbsent", "exists"], pruning: ["equals", "in", "startsWith"], absent: true },
      flavor_text: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not", "isAbsent", "exists"], pruning: [], absent: true },
      edhrec_rank: { kind: "number", operators: ["equals", "in", "gt", "gte", "lt", "lte", "not", "isAbsent", "exists"], pruning: ["equals", "in", "gt", "gte", "lt", "lte"], absent: true },
      penny_rank: { kind: "number", operators: ["equals", "in", "gt", "gte", "lt", "lte", "not", "isAbsent", "exists"], pruning: [], absent: true },
      promo_types: { kind: "json", operators: ["isAbsent", "exists"], pruning: [], absent: true },
      security_stamp: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not", "isAbsent", "exists"], pruning: [], absent: true },
      card_faces: { kind: "json", operators: ["isAbsent", "exists"], pruning: [], absent: true },
      preview: { kind: "json", operators: ["isAbsent", "exists"], pruning: [], absent: true },
      watermark: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not", "isAbsent", "exists"], pruning: [], absent: true },
      frame_effects: { kind: "json", operators: ["isAbsent", "exists"], pruning: [], absent: true },
      loyalty: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not", "isAbsent", "exists"], pruning: ["equals", "in", "startsWith"], absent: true },
      printed_name: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not", "isAbsent", "exists"], pruning: [], absent: true },
      resource_id: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not", "isAbsent", "exists"], pruning: [], absent: true },
      tcgplayer_etched_id: { kind: "number", operators: ["equals", "in", "gt", "gte", "lt", "lte", "not", "isAbsent", "exists"], pruning: [], absent: true },
      flavor_name: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not", "isAbsent", "exists"], pruning: [], absent: true },
      attraction_lights: { kind: "json", operators: ["isAbsent", "exists"], pruning: [], absent: true },
      color_indicator: { kind: "json", operators: ["isAbsent", "exists"], pruning: [], absent: true },
      printed_text: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not", "isAbsent", "exists"], pruning: [], absent: true },
      printed_type_line: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not", "isAbsent", "exists"], pruning: [], absent: true },
      power_num: { kind: "number", operators: ["equals", "in", "gt", "gte", "lt", "lte", "not", "isAbsent", "exists"], pruning: ["equals", "in", "gt", "gte", "lt", "lte"], absent: true },
      toughness_num: { kind: "number", operators: ["equals", "in", "gt", "gte", "lt", "lte", "not", "isAbsent", "exists"], pruning: ["equals", "in", "gt", "gte", "lt", "lte"], absent: true },
      loyalty_num: { kind: "number", operators: ["equals", "in", "gt", "gte", "lt", "lte", "not", "isAbsent", "exists"], pruning: ["equals", "in", "gt", "gte", "lt", "lte"], absent: true },
      name_fold: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not", "isAbsent", "exists"], pruning: ["equals", "in", "startsWith", "contains"], absent: true },
      type_line_fold: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not", "isAbsent", "exists"], pruning: ["equals", "in", "startsWith", "contains"], absent: true },
      oracle_text_fold: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not", "isAbsent", "exists"], pruning: ["equals", "in", "startsWith", "contains"], absent: true },
      artist_fold: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not", "isAbsent", "exists"], pruning: ["equals", "in", "startsWith", "contains"], absent: true },
      flavor_text_fold: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not", "isAbsent", "exists"], pruning: ["equals", "in", "startsWith", "contains"], absent: true },
      set_name_fold: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not", "isAbsent", "exists"], pruning: ["equals", "in", "startsWith", "contains"], absent: true },
    },
  },
} as const;

export type Schema = typeof schema;
