// generated by static-shard@0.0.0 — do not edit
import { createClient, type Collection, type ClientOptions, type GenericClient } from "static-shard";
import { schema, type Schema, type Records } from "./schema.js";

export interface Db {
  "default-cards-20260721211623": Collection<Schema["default-cards-20260721211623"], Records["default-cards-20260721211623"]>;
}

const DEFAULT_BASE_PATH = "/shard-data";

export function connect(opts?: Partial<ClientOptions>): Db {
  const generic: GenericClient<Schema, Records> = createClient<Schema, Records>(schema, {
    basePath: DEFAULT_BASE_PATH,
    ...opts,
  });
  return generic as unknown as Db;
}
