// generated by static-shard@0.0.0 — do not edit
export interface Default_cards_20260721211623 {
  object: string;
  id: string;
  oracle_id: string;
  multiverse_ids?: unknown;
  mtgo_id: number;
  arena_id: number;
  tcgplayer_id: number;
  cardmarket_id: number;
  name: string;
  lang: string;
  released_at: string;
  uri: string;
  scryfall_uri: string;
  layout: string;
  highres_image: boolean;
  image_status: string;
  image_updated_at: string;
  image_uris?: unknown;
  mana_cost: string;
  cmc: number;
  type_line: string;
  oracle_text: string;
  colors: string[];
  color_identity: string[];
  keywords: string[];
  produced_mana: string[];
  all_parts?: unknown;
  legalities?: unknown;
  games: string[];
  reserved: boolean;
  game_changer: boolean;
  foil: boolean;
  nonfoil: boolean;
  finishes: string[];
  oversized: boolean;
  promo: boolean;
  reprint: boolean;
  variation: boolean;
  set_id: string;
  set: string;
  set_name: string;
  set_type: string;
  set_uri: string;
  set_search_uri: string;
  scryfall_set_uri: string;
  rulings_uri: string;
  prints_search_uri: string;
  collector_number: string;
  digital: boolean;
  rarity: string;
  card_back_id: string;
  artist: string;
  artist_ids: string[];
  illustration_id: string;
  border_color: string;
  frame: string;
  full_art: boolean;
  textless: boolean;
  booster: boolean;
  story_spotlight: boolean;
  prices?: unknown;
  related_uris?: unknown;
  purchase_uris?: unknown;
  mtgo_foil_id: number;
  power: string;
  toughness: string;
  flavor_text: string;
  edhrec_rank: number;
  penny_rank: number;
  promo_types: string[];
  security_stamp: string;
  card_faces?: unknown;
  preview?: unknown;
  watermark: string;
  frame_effects: string[];
  loyalty: string;
  printed_name: string;
  resource_id: string;
  tcgplayer_etched_id: number;
  flavor_name?: string;
  attraction_lights?: unknown;
  color_indicator: string[];
  printed_text: string;
  printed_type_line: string;
}

export interface Records {
  "default-cards-20260721211623": Default_cards_20260721211623;
}

export const schema = {
  "default-cards-20260721211623": {
    pk: "id",
    fields: {
      object: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"] },
      id: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"], pk: true },
      oracle_id: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"] },
      mtgo_id: { kind: "number", operators: ["equals", "in", "not"] },
      arena_id: { kind: "number", operators: ["equals", "in", "not"] },
      tcgplayer_id: { kind: "number", operators: ["equals", "in", "not"] },
      cardmarket_id: { kind: "number", operators: ["equals", "in", "not"] },
      name: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"] },
      lang: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"] },
      released_at: { kind: "date", operators: ["equals", "in", "not"] },
      uri: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"] },
      scryfall_uri: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"] },
      layout: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"] },
      highres_image: { kind: "boolean", operators: ["equals", "not"] },
      image_status: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"] },
      image_updated_at: { kind: "date", operators: ["equals", "in", "gt", "gte", "lt", "lte", "not"] },
      mana_cost: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"] },
      cmc: { kind: "number", operators: ["equals", "in", "not"] },
      type_line: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"] },
      oracle_text: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"] },
      colors: { kind: "string", operators: ["equals", "in", "startsWith", "not"], multi: true },
      color_identity: { kind: "string", operators: ["equals", "in", "startsWith", "not"], multi: true },
      keywords: { kind: "string", operators: ["equals", "in", "startsWith", "not"], multi: true },
      produced_mana: { kind: "string", operators: ["equals", "in", "startsWith", "not"], multi: true },
      games: { kind: "string", operators: ["equals", "in", "startsWith", "not"], multi: true },
      reserved: { kind: "boolean", operators: ["equals", "not"] },
      game_changer: { kind: "boolean", operators: ["equals", "not"] },
      foil: { kind: "boolean", operators: ["equals", "not"] },
      nonfoil: { kind: "boolean", operators: ["equals", "not"] },
      finishes: { kind: "string", operators: ["equals", "in", "startsWith", "not"], multi: true },
      oversized: { kind: "boolean", operators: ["equals", "not"] },
      promo: { kind: "boolean", operators: ["equals", "not"] },
      reprint: { kind: "boolean", operators: ["equals", "not"] },
      variation: { kind: "boolean", operators: ["equals", "not"] },
      set_id: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"] },
      set: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"] },
      set_name: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"] },
      set_type: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"] },
      set_uri: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"] },
      set_search_uri: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"] },
      scryfall_set_uri: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"] },
      rulings_uri: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"] },
      prints_search_uri: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"] },
      collector_number: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"] },
      digital: { kind: "boolean", operators: ["equals", "not"] },
      rarity: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"] },
      card_back_id: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"] },
      artist: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"] },
      artist_ids: { kind: "string", operators: ["equals", "in", "startsWith", "not"], multi: true },
      illustration_id: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"] },
      border_color: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"] },
      frame: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"] },
      full_art: { kind: "boolean", operators: ["equals", "not"] },
      textless: { kind: "boolean", operators: ["equals", "not"] },
      booster: { kind: "boolean", operators: ["equals", "not"] },
      story_spotlight: { kind: "boolean", operators: ["equals", "not"] },
      mtgo_foil_id: { kind: "number", operators: ["equals", "in", "not"] },
      power: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"] },
      toughness: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"] },
      flavor_text: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"] },
      edhrec_rank: { kind: "number", operators: ["equals", "in", "not"] },
      penny_rank: { kind: "number", operators: ["equals", "in", "not"] },
      promo_types: { kind: "string", operators: ["equals", "in", "startsWith", "not"], multi: true },
      security_stamp: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"] },
      watermark: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"] },
      frame_effects: { kind: "string", operators: ["equals", "in", "startsWith", "not"], multi: true },
      loyalty: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"] },
      printed_name: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"] },
      resource_id: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"] },
      tcgplayer_etched_id: { kind: "number", operators: ["equals", "in", "not"] },
      flavor_name: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"], absent: true },
      color_indicator: { kind: "string", operators: ["equals", "in", "startsWith", "not"], multi: true },
      printed_text: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"] },
      printed_type_line: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"] },
    },
  },
} as const;

export type Schema = typeof schema;
